[package]
name = "booru-rs"
version = "0.1.1"
edition = "2021"
description = "An async Booru client for Rust"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/booru-rs"

[dependencies]
reqwest = { version = "0.11.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.147", features = ["derive"] }
